name: main

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update:
    if: github.repository == 'lazka/katwarn-api'
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    name: update-dump
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '.ci/requirements.txt'

      - name: Install deps
        run: |
          python -m pip install --user -r .ci/requirements.txt

      - name: Dump API
        run: |
          mkdir -p build
          python dump.py -o build/dump.json

      - name: Push dump
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: dump
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Build map
        run: |
          cp .ci/index.html ./build
          cp .ci/api.html ./build
          python folium_example.py -d build/dump.json -o build/map.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
