name: test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
  
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '.ci/requirements.txt'

      - name: Install deps
        run: |
          pipx install poetry
          poetry install

      - name: Test
        run: |
          poetry run pytest
